name: Versioning and releasing

on:
  workflow_call:
    secrets:
      RELEASE_IT_SSH_PRIVATE_KEY:
        required: true
    inputs:
      BUMPER:
        description: "set to true if release-it bumper plugin is needed, false otherwise."
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      BUMPER:
        required: true
        description: "set to true if release-it bumper plugin is needed, false otherwise."
        type: boolean
        default: false


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  manual-release-it:
    runs-on: ubuntu-latest
    environment:
      name: release-it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote rm origin
          git remote add origin git@github.com:${{ github.repository }}.git
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RELEASE_IT_SSH_PRIVATE_KEY }}
      - run: sudo npm install -g release-it @release-it/conventional-changelog @release-it/bumper
      - if: ${{ inputs.BUMPER }} == true
        run: sudo npm install -g @release-it/bumper
      - name: Release-it
        run: release-it --ci || git status
