name: Versioning and releasing

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release-it:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment:
      name: release-it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - run: sudo npm install -g release-it @release-it/conventional-changelog @release-it/bumper @j-ulrich/release-it-regex-bumper

      - name: Retrieve next release version
        id: retrieve_release_version
        run: |
          RELEASE_VERSION=$(release-it --release-version | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$')
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release-it
        run: release-it -VV --ci || git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: lupise/major-tagging-action@v0
